-- -- Enable the wrappers extension
-- CREATE EXTENSION IF NOT EXISTS wrappers WITH SCHEMA extensions;

-- -- Create the Stripe wrapper
-- CREATE FOREIGN DATA WRAPPER stripe_wrapper
--   HANDLER stripe_fdw_handler
--   VALIDATOR stripe_fdw_validator;

-- -- Create Stripe server
-- CREATE SERVER stripe_server
--   FOREIGN DATA WRAPPER stripe_wrapper
--   OPTIONS (
--     api_key_name 'STRIPE_SECRET_KEY', // Please replace with your own Stripe secret key
--     api_url 'https://api.stripe.com/v1/'
--   );

-- -- Create schema for Stripe tables
-- CREATE SCHEMA IF NOT EXISTS stripe;

-- -- Create customers table
-- CREATE FOREIGN TABLE stripe.customers (
--   id text,
--   email text,
--   name text,
--   description text,
--   created timestamp,
--   attrs jsonb
-- )
--   SERVER stripe_server
--   OPTIONS (
--     object 'customers',
--     rowid_column 'id'
--   );

-- -- Create subscriptions table
-- CREATE FOREIGN TABLE stripe.subscriptions (
--   id text,
--   customer text,
--   currency text,
--   current_period_start timestamp,
--   current_period_end timestamp,
--   status text,
--   cancel_at_period_end boolean,
--   created timestamp,
--   attrs jsonb
-- )
--   SERVER stripe_server
--   OPTIONS (
--     object 'subscriptions',
--     rowid_column 'id'
--   );

-- -- Create products table for subscription plans
-- CREATE FOREIGN TABLE stripe.products (
--   id text,
--   name text,
--   active boolean,
--   description text,
--   default_price text,
--   created timestamp,
--   updated timestamp,
--   attrs jsonb
-- )
--   SERVER stripe_server
--   OPTIONS (
--     object 'products',
--     rowid_column 'id'
--   );

-- -- Create prices table
-- CREATE FOREIGN TABLE stripe.prices (
--   id text,
--   active boolean,
--   currency text,
--   product text,
--   unit_amount bigint,
--   type text,
--   created timestamp,
--   attrs jsonb
-- )
--   SERVER stripe_server
--   OPTIONS (
--     object 'prices'
--   );