-- Learning Category
insert into rss_feeds (name, description, site_icon, url, language, is_active, categories) values
('The Decision Lab', 
 'Research and insights on decision making and behavioral science', 
 'https://thedecisionlab.com/favicon.ico', 
 'https://thedecisionlab.com/feed/', 
 'en', 
 false,
 array['critical_thinking', 'cognitive_science', 'psychology']::feed_category[]
),
('Ness Labs', 
 'The science of learning and mindful productivity', 
 'https://nesslabs.com/favicon.ico', 
 'https://nesslabs.com/feed', 
 'en', 
 false,
 array['learning_productivity', 'cognitive_science', 'personal_development']::feed_category[]
),
('Farnam Street', 
 'Mental models and learning how to think better', 
 'https://fs.blog/favicon.ico', 
 'https://fs.blog/feed/', 
 'en', 
 false,
 array['mental_models', 'critical_thinking', 'personal_development']::feed_category[]
);
-- Learning Category
insert into rss_feeds (name, description, site_icon, url, language, is_active, categories) values
('The Sunday Wisdom', 
 'Weekly insights on thinking, learning, and creativity', 
 'https://coffeeandjunk.substack.com/favicon.ico', 
 'https://coffeeandjunk.substack.com/feed', 
 'en', 
 false,
 array['learning_productivity', 'personal_development', 'critical_thinking']::feed_category[]
),
('Commonplace - The Commoncog Blog', 
 'Practical insights on learning and expertise', 
 'https://commoncog.com/favicon.ico', 
 'https://commoncog.com/blog/rss/', 
 'en', 
 false,
 array['learning_productivity', 'mental_models', 'critical_thinking']::feed_category[]
),
('Scott H Young', 
 'Learning strategies and personal development', 
 'https://scotthyoung.com/favicon.ico', 
 'https://feeds.feedburner.com/scotthyoung/HAHx', 
 'en', 
 false,
 array['learning_productivity', 'personal_development']::feed_category[]
),
('Big Think', 
 'Ideas and insights from thought leaders', 
 'https://bigthink.com/favicon.ico', 
 'https://feeds.feedburner.com/bigthink/main', 
 'en', 
 false,
 array['critical_thinking', 'research_papers', 'cognitive_science']::feed_category[]
);

-- Startup Category
insert into rss_feeds (name, description, site_icon, url, language, is_active, categories) values
('Steve Blank', 
 'Insights from a serial entrepreneur and startup mentor', 
 'https://steveblank.com/favicon.ico', 
 'http://steveblank.com/feed/', 
 'en', 
 false,
 array['entrepreneurship', 'startup_news', 'business_strategy']::feed_category[]
),
('George Hotz Blog', 
 'Thoughts on technology and entrepreneurship', 
 'https://geohot.github.io/favicon.ico', 
 'https://geohot.github.io/blog/feed.xml', 
 'en', 
 false,
 array['entrepreneurship', 'tech_news', 'artificial_intelligence']::feed_category[]
),
('Guy Kawasaki', 
 'Marketing and entrepreneurship insights', 
 'https://guykawasaki.com/favicon.ico', 
 'http://guykawasaki.com/feed/', 
 'en', 
 false,
 array['entrepreneurship', 'digital_marketing', 'business_strategy']::feed_category[]
),
('Benedict Evans', 
 'Analysis on tech and business strategy', 
 'https://ben-evans.com/favicon.ico', 
 'http://ben-evans.com/benedictevans?format=rss', 
 'en', 
 false,
 array['tech_news', 'business_strategy', 'venture_capital']::feed_category[]
),
('First Round Review', 
 'In-depth startup advice and insights', 
 'https://firstround.com/favicon.ico', 
 'http://firstround.com/review/feed.xml', 
 'en', 
 false,
 array['startup_news', 'venture_capital', 'leadership']::feed_category[]
),
('Sam Altman', 
 'Startup wisdom from Y Combinator president', 
 'https://blog.samaltman.com/favicon.ico', 
 'http://blog.samaltman.com/posts.atom', 
 'en', 
 false,
 array['startup_news', 'entrepreneurship', 'artificial_intelligence']::feed_category[]
),
('Andrew Chen', 
 'Essays on startups, growth, and network effects', 
 'https://andrewchen.com/favicon.ico', 
 'http://andrewchen.co/feed/', 
 'en', 
 false,
 array['startup_news', 'growth_marketing', 'product_management']::feed_category[]
),
('Both Sides of the Table', 
 'VC perspective on startups and entrepreneurship', 
 'https://bothsidesofthetable.com/favicon.ico', 
 'https://bothsidesofthetable.com/feed', 
 'en', 
 false,
 array['venture_capital', 'startup_news', 'business_strategy']::feed_category[]
),
('TechCrunch Startups', 
 'Latest startup news and funding updates', 
 'https://techcrunch.com/favicon.ico', 
 'https://techcrunch.com/startups/feed/', 
 'en', 
 false,
 array['startup_news', 'venture_capital', 'tech_news']::feed_category[]
),
('OnStartups', 
 'Practical advice for software entrepreneurs', 
 'https://onstartups.com/favicon.ico', 
 'http://feed.onstartups.com/onstartups', 
 'en', 
 false,
 array['entrepreneurship', 'startup_news', 'software_development']::feed_category[]
),
('The Black Box of Product Management', 
 'Insights into product management', 
 'https://medium.com/favicon.ico', 
 'https://medium.com/feed/the-black-box-of-product-management', 
 'en', 
 false,
 array['product_management', 'leadership', 'software_development']::feed_category[]
),
('Irrational Exuberance', 
 'Engineering management and startup scaling', 
 'https://lethain.com/favicon.ico', 
 'https://lethain.com/feeds/', 
 'en', 
 false,
 array['engineering_general', 'leadership', 'system_design']::feed_category[]
);

-- Tech News Category
insert into rss_feeds (name, description, site_icon, url, language, is_active, categories) values
('Fast Company', 
 'Innovation in technology and business', 
 'https://www.fastcompany.com/favicon.ico', 
 'http://www.fastcodesign.com/rss.xml', 
 'en', 
 false,
 array['tech_news', 'business_strategy', 'product_design']::feed_category[]
),
('Forbes - Entrepreneurs', 
 'Business news and entrepreneurship insights', 
 'https://www.forbes.com/favicon.ico', 
 'http://www.forbes.com/entrepreneurs/index.xml', 
 'en', 
 false,
 array['entrepreneurship', 'business_strategy', 'startup_news']::feed_category[]
),
('SlashGear', 
 'Latest technology news and reviews', 
 'https://www.slashgear.com/favicon.ico', 
 'http://feeds.slashgear.com/slashgear', 
 'en', 
 false,
 array['tech_news', 'product_design', 'mobile_development']::feed_category[]
),
('VentureBeat', 
 'Tech news, analysis, and innovation', 
 'https://venturebeat.com/favicon.ico', 
 'http://venturebeat.com/feed/', 
 'en', 
 false,
 array['tech_news', 'artificial_intelligence', 'startup_news']::feed_category[]
),
('The Verge', 
 'Technology, science, art, and culture', 
 'https://www.theverge.com/favicon.ico', 
 'http://www.theverge.com/rss/full.xml', 
 'en', 
 false,
 array['tech_news', 'product_design', 'artificial_intelligence']::feed_category[]
),
('Engadget', 
 'Latest technology news and gadgets', 
 'https://www.engadget.com/favicon.ico', 
 'http://www.engadget.com/rss-full.xml', 
 'en', 
 false,
 array['tech_news', 'mobile_development', 'artificial_intelligence']::feed_category[]
),
('Tech in Asia', 
 'Asian technology and startup news', 
 'https://techinasia.com/favicon.ico', 
 'https://feeds2.feedburner.com/PennOlson', 
 'en', 
 false,
 array['tech_news', 'startup_news', 'business_strategy']::feed_category[]
),
('Forbes - Leadership', 
 'Leadership insights and strategies', 
 'https://www.forbes.com/favicon.ico', 
 'https://www.forbes.com/leadership/feed/', 
 'en', 
 false,
 array['leadership', 'business_strategy', 'personal_development']::feed_category[]
);
-- Products & Ideas Category
insert into rss_feeds (name, description, site_icon, url, language, is_active, categories) values
('Product Hunt', 
 'Daily curation of best new products', 
 'https://producthunt.com/favicon.ico', 
 'http://www.producthunt.com/feed', 
 'en', 
 false,
 array['product_management', 'product_design', 'startup_news']::feed_category[]
),
('Hacker News: Show HN', 
 'Show and tell from the tech community', 
 'https://news.ycombinator.com/favicon.ico', 
 'http://hnrss.org/show', 
 'en', 
 false,
 array['software_development', 'product_management', 'tech_news']::feed_category[]
),
('Hacker News: Launches', 
 'New product launches and announcements', 
 'https://news.ycombinator.com/favicon.ico', 
 'https://hnrss.org/launches', 
 'en', 
 false,
 array['startup_news', 'product_management', 'tech_news']::feed_category[]
),
('Sachin Rekhi Blog', 
 'Product management and entrepreneurship', 
 'https://sachinrekhi.com/favicon.ico', 
 'http://feeds.feedburner.com/sachinrekhiblog', 
 'en', 
 false,
 array['product_management', 'entrepreneurship', 'business_strategy']::feed_category[]
);

-- Engineering Blogs Category
insert into rss_feeds (name, description, site_icon, url, language, is_active, categories) values
('The Pragmatic Engineer', 
 'Software engineering insights', 
 'https://blog.pragmaticengineer.com/favicon.ico', 
 'https://blog.pragmaticengineer.com/rss/', 
 'en', 
 false,
 array['engineering_general', 'system_design', 'software_development']::feed_category[]
),
('Airtable Engineering', 
 'Engineering insights from Airtable team', 
 'https://airtable.com/favicon.ico', 
 'https://medium.com/feed/airtable-eng', 
 'en', 
 false,
 array['engineering_general', 'data_engineering', 'frontend_engineering']::feed_category[]
),
('Medium Engineering', 
 'Engineering challenges at Medium', 
 'https://medium.com/favicon.ico', 
 'https://medium.com/feed/medium-eng', 
 'en', 
 false,
 array['engineering_general', 'web_development', 'infrastructure']::feed_category[]
),
('PayPal Engineering', 
 'Technical insights from PayPal', 
 'https://paypal.com/favicon.ico', 
 'https://medium.com/feed/paypal-engineering', 
 'en', 
 false,
 array['engineering_general', 'system_design', 'infrastructure']::feed_category[]
),
('Pinterest Engineering', 
 'Engineering at Pinterest', 
 'https://pinterest.com/favicon.ico', 
 'https://medium.com/feed/pinterest-engineering', 
 'en', 
 false,
 array['engineering_general', 'data_engineering', 'infrastructure']::feed_category[]
),
('Grab Tech', 
 'Engineering insights from Grab', 
 'https://grab.com/favicon.ico', 
 'http://engineering.grab.com/feed.xml', 
 'en', 
 false,
 array['engineering_general', 'mobile_development', 'system_design']::feed_category[]
),
('Slack Engineering', 
 'Building Slack', 
 'https://slack.com/favicon.ico', 
 'https://slack.engineering/feed', 
 'en', 
 false,
 array['engineering_general', 'infrastructure', 'frontend_engineering']::feed_category[]
),
('GitHub Engineering', 
 'How GitHub builds GitHub', 
 'https://github.com/favicon.ico', 
 'http://githubengineering.com/atom.xml', 
 'en', 
 false,
 array['engineering_general', 'infrastructure', 'system_design']::feed_category[]
),
('Spotify Engineering', 
 'Engineering culture at Spotify', 
 'https://spotify.com/favicon.ico', 
 'http://labs.spotify.com/feed/', 
 'en', 
 false,
 array['engineering_general', 'data_engineering', 'infrastructure']::feed_category[]
),
('Twitter Engineering', 
 'Building Twitter', 
 'https://twitter.com/favicon.ico', 
 'https://blog.twitter.com/engineering/en_us/blog.rss', 
 'en', 
 false,
 array['engineering_general', 'infrastructure', 'system_design']::feed_category[]
),
('Stripe Blog', 
 'Building economic infrastructure', 
 'https://stripe.com/favicon.ico', 
 'https://stripe.com/blog/feed.rss', 
 'en', 
 false,
 array['engineering_general', 'infrastructure', 'system_design']::feed_category[]
),
('Instagram Engineering', 
 'Engineering at Instagram', 
 'https://instagram.com/favicon.ico', 
 'https://instagram-engineering.com/feed', 
 'en', 
 false,
 array['engineering_general', 'infrastructure', 'mobile_development']::feed_category[]
),
('Cloudflare Blog', 
 'Internet security and performance', 
 'https://cloudflare.com/favicon.ico', 
 'https://blog.cloudflare.com/rss/', 
 'en', 
 false,
 array['infrastructure', 'cybersecurity', 'system_design']::feed_category[]
),
('Asana Engineering', 
 'Building team productivity', 
 'https://asana.com/favicon.ico', 
 'https://blog.asana.com/category/eng/feed/', 
 'en', 
 false,
 array['engineering_general', 'frontend_engineering', 'infrastructure']::feed_category[]
),
('Canva Engineering', 
 'Engineering at Canva', 
 'https://canva.com/favicon.ico', 
 'https://engineering.canva.com/rss', 
 'en', 
 false,
 array['engineering_general', 'frontend_engineering', 'infrastructure']::feed_category[]
),
('Airbnb Tech', 
 'Engineering at Airbnb', 
 'https://airbnb.com/favicon.ico', 
 'https://medium.com/feed/airbnb-engineering', 
 'en', 
 false,
 array['engineering_general', 'infrastructure', 'data_engineering']::feed_category[]
);

-- Machine Learning Category
insert into rss_feeds (name, description, site_icon, url, language, is_active, categories) values
('ML@CMU', 
 'Machine learning research from CMU', 
 'https://blog.ml.cmu.edu/favicon.ico', 
 'https://blog.ml.cmu.edu/feed/', 
 'en', 
 false,
 array['machine_learning', 'artificial_intelligence', 'research_papers']::feed_category[]
),
('DeepMind', 
 'Latest in AI research from DeepMind', 
 'https://deepmind.com/favicon.ico', 
 'https://deepmind.com/blog/feed/basic/', 
 'en', 
 false,
 array['artificial_intelligence', 'machine_learning', 'deep_learning']::feed_category[]
),
('Jay Alammar', 
 'Visualizing machine learning concepts', 
 'https://jalammar.github.io/favicon.ico', 
 'https://jalammar.github.io/feed.xml', 
 'en', 
 false,
 array['machine_learning', 'deep_learning', 'nlp']::feed_category[]
),
('Distill', 
 'Clear explanations of machine learning', 
 'https://distill.pub/favicon.ico', 
 'http://distill.pub/rss.xml', 
 'en', 
 false,
 array['machine_learning', 'deep_learning', 'artificial_intelligence']::feed_category[]
),
('Lil Log', 
 'Deep learning and AI research notes', 
 'https://lilianweng.github.io/favicon.ico', 
 'https://lilianweng.github.io/lil-log/feed.xml', 
 'en', 
 false,
 array['deep_learning', 'machine_learning', 'artificial_intelligence']::feed_category[]
),
('MIT AI News', 
 'Latest in AI research from MIT', 
 'https://news.mit.edu/favicon.ico', 
 'http://news.mit.edu/rss/topic/artificial-intelligence2', 
 'en', 
 false,
 array['artificial_intelligence', 'research_papers', 'machine_learning']::feed_category[]
),
('BAIR Blog', 
 'Berkeley AI Research insights', 
 'https://bair.berkeley.edu/favicon.ico', 
 'http://bair.berkeley.edu/blog/feed.xml', 
 'en', 
 false,
 array['artificial_intelligence', 'machine_learning', 'research_papers']::feed_category[]
),
('OpenAI', 
 'Advanced AI research and deployment', 
 'https://openai.com/favicon.ico', 
 'https://blog.openai.com/rss/', 
 'en', 
 false,
 array['artificial_intelligence', 'machine_learning', 'nlp']::feed_category[]
),
('Google AI Blog', 
 'AI research from Google', 
 'https://ai.google/favicon.ico', 
 'http://googleresearch.blogspot.com/atom.xml', 
 'en', 
 false,
 array['artificial_intelligence', 'machine_learning', 'deep_learning']::feed_category[]
);

-- Design Category
insert into rss_feeds (name, description, site_icon, url, language, is_active, categories) values
('UX Planet', 
 'UX design articles and resources', 
 'https://uxplanet.org/favicon.ico', 
 'https://uxplanet.org/feed', 
 'en', 
 false,
 array['ux_design', 'interaction_design', 'product_design']::feed_category[]
),
('Nielsen Norman Group', 
 'Research-based UX insights', 
 'https://www.nngroup.com/favicon.ico', 
 'https://www.nngroup.com/feed/rss/', 
 'en', 
 false,
 array['ux_design', 'interaction_design', 'research_papers']::feed_category[]
),
('UX Movement', 
 'UX design patterns and solutions', 
 'https://uxmovement.com/favicon.ico', 
 'http://feeds.feedburner.com/uxmovement', 
 'en', 
 false,
 array['ux_design', 'interaction_design', 'ui_design']::feed_category[]
),
('Inside Design', 
 'InVision design blog', 
 'https://www.invisionapp.com/favicon.ico', 
 'http://blog.invisionapp.com/feed/', 
 'en', 
 false,
 array['product_design', 'design_systems', 'ui_design']::feed_category[]
),
('Smashing Magazine', 
 'Web design and development', 
 'https://www.smashingmagazine.com/favicon.ico', 
 'https://www.smashingmagazine.com/feed/', 
 'en', 
 false,
 array['web_design', 'web_development', 'frontend_engineering']::feed_category[]
),
('UX Collective', 
 'Curated UX design stories', 
 'https://uxdesign.cc/favicon.ico', 
 'https://uxdesign.cc/feed', 
 'en', 
 false,
 array['ux_design', 'product_design', 'interaction_design']::feed_category[]
),
('Airbnb Design', 
 'Design at Airbnb', 
 'https://airbnb.design/favicon.ico', 
 'http://airbnb.design/feed/', 
 'en', 
 false,
 array['design_systems', 'product_design', 'ux_design']::feed_category[]
),
('web.dev', 
 'Web development best practices', 
 'https://web.dev/favicon.ico', 
 'https://web.dev/feed.xml', 
 'en', 
 false,
 array['web_development', 'web_design', 'frontend_engineering']::feed_category[]
),
('CSS-Tricks', 
 'CSS tips and techniques', 
 'https://css-tricks.com/favicon.ico', 
 'https://feeds.feedburner.com/CssTricks', 
 'en', 
 false,
 array['web_development', 'frontend_engineering', 'web_design']::feed_category[]
);

-- Psychology Category
insert into rss_feeds (name, description, site_icon, url, language, is_active, categories) values
('PsyBlog', 
 'Scientific insights into psychology', 
 'https://www.spring.org.uk/favicon.ico', 
 'http://feeds.feedburner.com/PsychologyBlog', 
 'en', 
 false,
 array['psychology', 'cognitive_science', 'research_papers']::feed_category[]
),
('Psychology Today', 
 'Popular psychology insights', 
 'https://www.psychologytoday.com/favicon.ico', 
 'https://www.psychologytoday.com/intl/rss.xml', 
 'en', 
 false,
 array['psychology', 'cognitive_science', 'personal_development']::feed_category[]
),
('Psychology Headlines', 
 'Latest psychology research news', 
 'https://www.socialpsychology.org/favicon.ico', 
 'http://www.socialpsychology.org/headlines.rss', 
 'en', 
 false,
 array['psychology', 'research_papers', 'cognitive_science']::feed_category[]
),
('Nautilus', 
 'Science and psychology insights', 
 'https://nautil.us/favicon.ico', 
 'https://nautil.us/rss/all', 
 'en', 
 false,
 array['psychology', 'cognitive_science', 'research_papers']::feed_category[]
),
('Freakonomics', 
 'Psychology of economics and behavior', 
 'https://freakonomics.com/favicon.ico', 
 'http://freakonomics.blogs.nytimes.com/feed/', 
 'en', 
 false,
 array['psychology', 'data_analytics', 'research_papers']::feed_category[]
);

-- Science Category
insert into rss_feeds (name, description, site_icon, url, language, is_active, categories) values
('Quanta Magazine', 
 'Science and mathematics news', 
 'https://www.quantamagazine.org/favicon.ico', 
 'http://www.quantamagazine.org/feed/', 
 'en', 
 false,
 array['research_papers', 'computer_science', 'data_science']::feed_category[]
),
('Nature', 
 'Leading international science journal', 
 'https://www.nature.com/favicon.ico', 
 'http://www.nature.com/nature/current_issue/rss', 
 'en', 
 false,
 array['research_papers', 'artificial_intelligence', 'cognitive_science']::feed_category[]
),
('MIT Technology News', 
 'Latest technology research from MIT', 
 'https://news.mit.edu/favicon.ico', 
 'https://news.mit.edu/rss/research', 
 'en', 
 false,
 array['tech_news', 'artificial_intelligence', 'research_papers']::feed_category[]
),
('ScienceAlert', 
 'Latest discoveries in science', 
 'https://www.sciencealert.com/favicon.ico', 
 'https://www.sciencealert.com/rss', 
 'en', 
 false,
 array['research_papers', 'cognitive_science', 'artificial_intelligence']::feed_category[]
),
('Singularity Hub', 
 'Future science and technology', 
 'https://singularityhub.com/favicon.ico', 
 'https://singularityhub.com/feed/', 
 'en', 
 false,
 array['artificial_intelligence', 'tech_news', 'research_papers']::feed_category[]
);

-- Neuroscience Category
insert into rss_feeds (name, description, site_icon, url, language, is_active, categories) values
('Neuroscience News', 
 'Latest neuroscience research', 
 'https://neurosciencenews.com/favicon.ico', 
 'http://neurosciencenews.com/feed/', 
 'en', 
 false,
 array['neuroscience', 'cognitive_science', 'research_papers']::feed_category[]
),
('ScienceDaily Neuroscience', 
 'Daily neuroscience updates', 
 'https://www.sciencedaily.com/favicon.ico', 
 'https://sciencedaily.com/rss/mind_brain/neuroscience.xml', 
 'en', 
 false,
 array['neuroscience', 'cognitive_science', 'research_papers']::feed_category[]
),
('SharpBrains', 
 'Brain science and health', 
 'https://sharpbrains.com/favicon.ico', 
 'http://www.sharpbrains.com/feed/', 
 'en', 
 false,
 array['neuroscience', 'cognitive_science', 'personal_development']::feed_category[]
);

-- Marketing Category
insert into rss_feeds (name, description, site_icon, url, language, is_active, categories) values
('Moz Blog', 
 'SEO and online marketing insights', 
 'https://moz.com/favicon.ico', 
 'http://feeds.feedburner.com/seomoz', 
 'en', 
 false,
 array['seo', 'digital_marketing', 'content_marketing']::feed_category[]
),
('Content Marketing Institute', 
 'Content marketing strategy', 
 'https://contentmarketinginstitute.com/favicon.ico', 
 'http://feeds.feedburner.com/cmi-content-marketing', 
 'en', 
 false,
 array['content_marketing', 'digital_marketing', 'marketing_analytics']::feed_category[]
),
('Neil Patel', 
 'Digital marketing strategies', 
 'https://neilpatel.com/favicon.ico', 
 'http://feeds.feedburner.com/KISSmetrics', 
 'en', 
 false,
 array['digital_marketing', 'seo', 'growth_marketing']::feed_category[]
),
('MarketingProfs', 
 'Marketing resources and training', 
 'https://www.marketingprofs.com/favicon.ico', 
 'http://rss.marketingprofs.com/marketingprofs/daily', 
 'en', 
 false,
 array['digital_marketing', 'content_marketing', 'marketing_analytics']::feed_category[]
),
('Quick Sprout', 
 'Online marketing and growth', 
 'https://www.quicksprout.com/favicon.ico', 
 'http://www.quicksprout.com/feed/', 
 'en', 
 false,
 array['growth_marketing', 'digital_marketing', 'seo']::feed_category[]
),
('Social Media Examiner', 
 'Social media marketing tactics', 
 'https://www.socialmediaexaminer.com/favicon.ico', 
 'http://www.socialmediaexaminer.com/feed/', 
 'en', 
 false,
 array['social_media', 'digital_marketing', 'content_marketing']::feed_category[]
),
('Convince and Convert', 
 'Digital marketing strategy', 
 'https://www.convinceandconvert.com/favicon.ico', 
 'http://www.convinceandconvert.com/feed/', 
 'en', 
 false,
 array['digital_marketing', 'content_marketing', 'social_media']::feed_category[]
),
('Hubspot Blog', 
 'Inbound marketing and sales', 
 'https://www.hubspot.com/favicon.ico', 
 'http://blog.hubspot.com/marketing/rss.xml', 
 'en', 
 false,
 array['digital_marketing', 'growth_marketing', 'content_marketing']::feed_category[]
),
('Seth Godin', 
 'Marketing thought leadership', 
 'https://seths.blog/favicon.ico', 
 'http://sethgodin.typepad.com/seths_blog/atom.xml', 
 'en', 
 false,
 array['digital_marketing', 'leadership', 'growth_marketing']::feed_category[]
),
('Backlinko', 
 'SEO and content marketing', 
 'https://backlinko.com/favicon.ico', 
 'http://backlinko.com/feed', 
 'en', 
 false,
 array['seo', 'content_marketing', 'digital_marketing']::feed_category[]
);

-- Additional Technical Blogs
insert into rss_feeds (name, description, site_icon, url, language, is_active, categories) values
('Julia Evans', 
 'Programming and systems', 
 'https://jvns.ca/favicon.ico', 
 'https://jvns.ca/atom.xml', 
 'en', 
 false,
 array['software_development', 'system_design', 'infrastructure']::feed_category[]
),
('Martin Kleppmann', 
 'Distributed systems and data', 
 'https://martin.kleppmann.com/favicon.ico', 
 'https://feeds.feedburner.com/martinkl?format=xml', 
 'en', 
 false,
 array['system_design', 'data_engineering', 'infrastructure']::feed_category[]
),
('Dan Abramov', 
 'JavaScript and React insights', 
 'https://overreacted.io/favicon.ico', 
 'https://overreacted.io/rss.xml', 
 'en', 
 false,
 array['frontend_engineering', 'web_development', 'software_development']::feed_category[]
),
('Dan Luu', 
 'Computer science and engineering', 
 'https://danluu.com/favicon.ico', 
 'https://danluu.com/atom.xml', 
 'en', 
 false,
 array['computer_science', 'system_design', 'engineering_general']::feed_category[]
),
('Josh Comeau', 
 'Web development and React', 
 'https://joshwcomeau.com/favicon.ico', 
 'https://joshwcomeau.com/rss.xml', 
 'en', 
 false,
 array['frontend_engineering', 'web_development', 'web_design']::feed_category[]
),
('Sophie Alpert', 
 'React and engineering', 
 'https://sophiebits.com/favicon.ico', 
 'https://sophiebits.com/atom.xml', 
 'en', 
 false,
 array['frontend_engineering', 'web_development', 'software_development']::feed_category[]
),
('Signal Blog', 
 'Privacy and security', 
 'https://signal.org/favicon.ico', 
 'https://signal.org/blog/rss.xml', 
 'en', 
 false,
 array['cybersecurity', 'infrastructure', 'system_design']::feed_category[]
),
('Joel on Software', 
 'Software development insights', 
 'https://www.joelonsoftware.com/favicon.ico', 
 'https://www.joelonsoftware.com/feed/', 
 'en', 
 false,
 array['software_development', 'engineering_general', 'product_management']::feed_category[]
);

-- Other Notable Feeds
insert into rss_feeds (name, description, site_icon, url, language, is_active, categories) values
('TED Talks', 
 'Ideas worth spreading', 
 'https://www.ted.com/favicon.ico', 
 'http://feeds.feedburner.com/tedtalks_video', 
 'en', 
 false,
 array['personal_development', 'tech_news', 'leadership']::feed_category[]
),
('Harvard Business Review', 
 'Business management insights', 
 'https://hbr.org/favicon.ico', 
 'http://feeds.harvardbusiness.org/harvardbusiness/', 
 'en', 
 false,
 array['leadership', 'business_strategy', 'personal_development']::feed_category[]
);
-- Additional Notable Feeds Continued
insert into rss_feeds (name, description, site_icon, url, language, is_active, categories) values
('InfoQ', 
 'Software development news and trends', 
 'https://www.infoq.com/favicon.ico', 
 'https://feed.infoq.com/', 
 'en', 
 false,
 array['software_development', 'engineering_general', 'web_development']::feed_category[]
),
('ReadWrite', 
 'IoT and emerging technology', 
 'https://readwrite.com/favicon.ico', 
 'https://readwrite.com/feed/', 
 'en', 
 false,
 array['tech_news', 'mobile_development', 'software_development']::feed_category[]
),
('AngelList Weekly', 
 'Startup and venture capital insights', 
 'https://angel.co/favicon.ico', 
 'https://angel.co/newsletters/feed', 
 'en', 
 false,
 array['startup_news', 'venture_capital', 'business_strategy']::feed_category[]
),
('Stack Overflow Blog', 
 'Programming and developer community insights', 
 'https://stackoverflow.blog/favicon.ico', 
 'https://stackoverflow.blog/feed/', 
 'en', 
 false,
 array['software_development', 'engineering_general', 'web_development']::feed_category[]
),
('Fast.ai', 
 'Making AI more accessible', 
 'https://www.fast.ai/favicon.ico', 
 'https://www.fast.ai/index.xml', 
 'en', 
 false,
 array['artificial_intelligence', 'machine_learning', 'deep_learning']::feed_category[]
),
('DZone', 
 'Programming and development resources', 
 'https://dzone.com/favicon.ico', 
 'http://feeds.dzone.com/home', 
 'en', 
 false,
 array['software_development', 'web_development', 'engineering_general']::feed_category[]
),
('O Reilly Radar', 
 'Emerging technology trends', 
 'https://www.oreilly.com/favicon.ico', 
 'https://www.oreilly.com/radar/feed/index.xml', 
 'en', 
 false,
 array['tech_news', 'artificial_intelligence', 'software_development']::feed_category[]
),
('freeCodeCamp', 
 'Programming tutorials and tech articles', 
 'https://www.freecodecamp.org/favicon.ico', 
 'https://www.freecodecamp.org/news/rss/', 
 'en', 
 false,
 array['software_development', 'web_development', 'engineering_general']::feed_category[]
),
('Dev.to', 
 'Community of software developers', 
 'https://dev.to/favicon.ico', 
 'https://dev.to/feed', 
 'en', 
 false,
 array['software_development', 'web_development', 'frontend_engineering']::feed_category[]
),
('High Scalability', 
 'Building scalable websites', 
 'http://highscalability.com/favicon.ico', 
 'http://feeds.feedburner.com/HighScalability', 
 'en', 
 false,
 array['system_design', 'infrastructure', 'engineering_general']::feed_category[]
),
('Netflix Tech Blog', 
 'Netflix engineering insights', 
 'https://netflixtechblog.com/favicon.ico', 
 'https://netflixtechblog.com/feed', 
 'en', 
 false,
 array['engineering_general', 'system_design', 'infrastructure']::feed_category[]
),
('Uber Engineering Blog', 
 'Engineering challenges at Uber', 
 'https://eng.uber.com/favicon.ico', 
 'https://eng.uber.com/feed/', 
 'en', 
 false,
 array['engineering_general', 'system_design', 'data_engineering']::feed_category[]
),
('Android Developers Blog', 
 'Official Android development news', 
 'https://developer.android.com/favicon.ico', 
 'https://android-developers.googleblog.com/feeds/posts/default', 
 'en', 
 false,
 array['mobile_development', 'software_development', 'engineering_general']::feed_category[]
),
('Chrome Developers Blog', 
 'Chrome and web platform updates', 
 'https://developer.chrome.com/favicon.ico', 
 'https://developer.chrome.com/feeds/blog.xml', 
 'en', 
 false,
 array['web_development', 'frontend_engineering', 'software_development']::feed_category[]
),
('AWS Blog', 
 'Amazon Web Services news and updates', 
 'https://aws.amazon.com/favicon.ico', 
 'https://aws.amazon.com/blogs/aws/feed/', 
 'en', 
 false,
 array['infrastructure', 'system_design', 'engineering_general']::feed_category[]
);

-- Additional Notable Feeds
insert into rss_feeds (name, description, site_icon, url, language, is_active, categories) values
('WIRED', 
 'Technology and cultural trends', 
 'https://www.wired.com/favicon.ico', 
 'https://www.wired.com/feed/rss', 
 'en', 
 false,
 array['tech_news', 'cybersecurity', 'artificial_intelligence']::feed_category[]
),
('Ars Technica', 
 'Technology news and analysis', 
 'https://arstechnica.com/favicon.ico', 
 'http://feeds.arstechnica.com/arstechnica/index', 
 'en', 
 false,
 array['tech_news', 'software_development', 'cybersecurity']::feed_category[]
),
('McKinsey Insights', 
 'Business and technology insights', 
 'https://www.mckinsey.com/favicon.ico', 
 'https://www.mckinsey.com/insights/rss', 
 'en', 
 false,
 array['business_strategy', 'leadership', 'tech_news']::feed_category[]
),
('Stanford AI Lab Blog', 
 'AI research from Stanford', 
 'https://ai.stanford.edu/favicon.ico', 
 'http://ai.stanford.edu/blog/feed.xml', 
 'en', 
 false,
 array['artificial_intelligence', 'machine_learning', 'research_papers']::feed_category[]
),
('ACM Queue', 
 'Software engineering practice', 
 'https://queue.acm.org/favicon.ico', 
 'https://queue.acm.org/rss/feeds/queuecontent.xml', 
 'en', 
 false,
 array['software_development', 'system_design', 'engineering_general']::feed_category[]
);