name: pr-agent

on:
  pull_request:
    types: [opened, reopened, synchronize]
  issue_comment:
    types: [created, edited]

permissions:
  pull-requests: write
  issues: write
  contents: write

jobs:
  pr_agent:
    runs-on: ubuntu-latest
    name: Run PR Agent
    if: ${{ github.event.sender.type != 'Bot' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run PR Agent
        id: pr-agent
        uses: Codium-ai/pr-agent@main
        env:
          OPENAI_KEY: ${{ secrets.OPENAI_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_ACTION_CONFIG.AUTO_DESCRIBE: "true"
          GITHUB_ACTION_CONFIG.AUTO_REVIEW: "true"
          GITHUB_ACTION_CONFIG.AUTO_IMPROVE: "true"
          PR_DESCRIPTION.USE_DESCRIPTION_MARKERS: "true"
          PR_REVIEWER.EXTRA_INSTRUCTIONS: "Provide meaningful feedback."
          PR_DESCRIPTION.EXTRA_INSTRUCTIONS: "Ensure descriptions are in English. Titles must follow commitlint conventions."
        with:
          config-file: ./.github/pr-agent-config.ini
