name: 'functions-tests'
on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - uses: supabase/setup-cli@v1
        with:
          version: latest
      - run: supabase start
      - run: |
          cd supabase/functions
          deno task test