name: Sync develop to main

on:
  push:
    branches:
      - develop
  pull_request:
    types: [closed]
    branches:
      - develop

jobs:
  sync-develop-to-main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: Check for existing PR
        id: check-pr
        uses: actions/github-script@v6
        with:
          script: |
            const { data: pullRequests } = await github.pulls.list({
              owner: context.repo.owner,
              repo: context.repo.repo,
              head: `develop`,
              base: `main`,
              state: 'open',
            });
            if (pullRequests.length > 0) {
              core.setOutput('pr_number', pullRequests[0].number);
            } else {
              core.setOutput('pr_number', '');
            }
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Update existing PR
        if: ${{ steps.check-pr.outputs.pr_number != '' }}
        run: |
          echo "Updating existing PR #${{ steps.check-pr.outputs.pr_number }}"
          gh pr comment ${{ steps.check-pr.outputs.pr_number }} --body "New updates pushed to develop. Review changes!"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create a new PR
        if: ${{ steps.check-pr.outputs.pr_number == '' }}
        run: |
          echo "Creating a new PR"
          gh pr create --base main --head develop --title "Sync develop to main" --body "This PR merges changes from develop into main."
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
