name: Sync develop to main

on:
  push:
    branches:
      - develop
  pull_request:
    types: [closed]
    branches:
      - develop

jobs:
  sync-develop-to-main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up GitHub CLI
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - run: npm install -g @actions/github-script

      - name: Configure Git
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: Check for existing PR
        id: check-pr
        run: |
          PR=$(gh pr list --base main --head develop --json number --jq '.[].number')
          echo "PR_NUMBER=$PR" >> $GITHUB_ENV
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Update existing PR
        if: env.PR_NUMBER != ''
        run: |
          echo "Updating existing PR #${PR_NUMBER}."
          gh pr comment $PR_NUMBER --body "New updates pushed to develop. Review changes!"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create a new PR
        if: env.PR_NUMBER == ''
        run: |
          echo "No existing PR found. Creating a new one."
          gh pr create --base main --head develop --title "Sync develop to main" --body "This PR merges changes from develop into main."
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
